FROM kalilinux/kali-rolling

RUN apt-get update \
&& apt-get upgrade -y \
&& apt-get install telnet -y \
&& apt-get install vim -y \
&& apt-get install net-tools -y \
&& apt-get install iputils-ping -y \
&& apt-get install nmap -y \
&& apt-get install hping3 -y 
